### ISSUE TITLE
Komplettering file contains samples that should not be uploaded

### ISSUE THREAD

**Issue by talnor** [Clinical-Genomics/MUTANT#108]
**What needs to be done:**
Should or can "kompletterings" file to FoHM contain lines for samples that should not be delivered to them?
Are these lines removed by cg during delivery?

**Suggestions on how to get it done:**
TBD

**What are the arguments for getting it done:**
TBD

**Task is considered finished when:**
TBD

**Notes**
in e.g. ablebobcat "760102_komplettering.csv":
test21CS508017,Vaccinationsgenombrott

**Comment by Mropat** [comment]
Suggestion:
Use regexp to filter which samples are allowed in komplettering:
only strings containing "21CS\(|\)|\d{6}" as in [this implementation ](https://github.com/Clinical-Genomics/cg/blob/d5dacd88a9a2c432aa5d88c01d3c5ab250ce9410/cg/meta/upload/fohm/fohm.py#L76)

**Comment by henningonsbring** [comment]
Using the regexp `SARS_COV_REGEX = "^[0-9]{2}CS[0-9]{6}$"` in cg https://github.com/Clinical-Genomics/cg/blob/master/cg/constants/constants.py

Only samples following the regexp (two digits followed by "CS" followed by six digits) will be delivered.
