### ISSUE TITLE
Update list of SARS-CoV-2 variants of concern, variants of interest, and variants under monitoring

### ISSUE THREAD

**Issue by sofstam** [Clinical-Genomics/MUTANT#111]
Update list of SARS-CoV-2 variants of concern, variants of interest and variants under monitoring according to ECDC:

https://www.ecdc.europa.eu/sites/default/files/documents/Variants-page-changelog-21-10.pdf

**What needs to be done:**
File classifications.csv needs to be updated

**Comment by talnor** [comment]
Done.
