### ISSUE TITLE
Varying primer sets

### ISSUE THREAD

**Issue by talnor** [Clinical-Genomics/MUTANT#113]
**What needs to be done:**
The SARS-CoV-2 prep can be performed with different primer sets and different versions of these. Currently supported primers are the artic set. The version is specified in the artic config.

We  will likely need to update this version, so it would be good to define a variable for this when running the analysis. 

TBD

**Suggestions on how to get it done:**
TBD

**What are the arguments for getting it done:**
TBD

**Task is considered finished when:**
TBD

**Comment by henningonsbring** [comment]
There is now "Primer" in the orderform, there the one placing the order will choose something like "Illumina artic v3" which will then choose the `/home/proj/production/mutant/MUTANT/mutant/config/hasta/illumina_artic_v3.json` config. When adding a new primer then a new config should be created with corresponding settings needed and that option should be supported in the orderform.

E.g. if adding artic v4.1 then create `/home/proj/production/mutant/MUTANT/mutant/config/hasta/illumina_artic_v4.1.json` with corresponding settings, add the bed files, and add into orderform the option "Illumina artic v4.1".
