### ISSUE TITLE
Updates needed for pangolin v.4

### ISSUE THREAD

**Issue by talnor** [Clinical-Genomics/MUTANT#136]
**What needs to be done:**
The latest release of pangolin version 4 introduces changes that are not compatible with gms-artic or MUTANT as of yet. 

More information is available in https://github.com/genomic-medicine-sweden/gms-artic/issues/52

For MUTANT, the new pangolin output sent to FoHM needs to be named as `pangolin_classification_format4.txt`

It is important to use the latest version of pangolin so we are up to date with the newest SARS-CoV-2 variants.

**Suggestions on how to get it done:**
- [x] Finish [draft PR](https://github.com/genomic-medicine-sweden/gms-artic/pull/53) in gms-artic to handle pangolin v4
- Then update version of gms-artic used by MUTANT
- Change FoHM pangolin output to `pangolin_classification_format4.txt`

**What are the arguments for getting it done:**

**Task is considered finished when:**
Mutant can run pangolin v.4 and creates an output file named as above.

**Comment by talnor** [comment]
@henningonsbring @sofstam

**Comment by talnor** [comment]
Made a second issue for changes that might affect KS (format of the KS report). I think we should not change that in this issue. https://github.com/Clinical-Genomics/MUTANT/issues/137

**Comment by henningonsbring** [comment]
this is in production now
