### ISSUE TITLE
Change name of PangoLEARN_version in KS results report

### ISSUE THREAD

**Issue by talnor** [Clinical-Genomics/MUTANT#137]
**What needs to be done:**
With pangolin v4 PangoLEARN will no longer be used. Instead pangolin_data will be used. The column header in the KS report should therefore be renamed. `pangolin_data_version` or `version` could work.

KS imports the file to their systems automatically and changing column headers or format of this file could give errors on the KS end.

**Suggestions on how to get it done:**
- Ask KS if changing column headers would affect the automation of the data import at KS
- If so, ask when would be a good time to update the column header.
- update the column header in mutant

**What are the arguments for getting it done:**

**Task is considered finished when:**
- KS has given us go ahead and the report is updated to give a more suitable column header.

**Comment by talnor** [comment]
Asked the hospital about this (JA). He says the column number is important, but not the heading. So we can go ahead and change the header name.

**Comment by henningonsbring** [comment]
ok, then I suggest we use the actual header that it truly is, but which column should we use? We can choose from these columns:
`taxon,lineage,conflict,ambiguity_score,scorpio_call,scorpio_support,scorpio_conflict,scorpio_notes,version,pangolin_version,scorpio_version,constellation_version,is_designated,qc_status,qc_notes,note`

Can we use `pangolin_version` as header? and then the information regarding pangolin_version? pangolin_version to me seems most similar to pangoLEARN, alternatively constellation_version

**Comment by talnor** [comment]
pangoLEARN repo has been replaced with the pangolin_data repo (this is the input data used by pangolin). It is named `version` in the new format.

**Comment by sofstam** [comment]
I am wondering if the column` is_designated` should be substituted as well since it is both `pango_LEARN` and `pango_designation` that will be deprecated in the future.

**Comment by talnor** [comment]
> I am wondering if the column` is_designated` should be substituted as well since it is both `pango_LEARN` and `pango_designation` that will be deprecated in the future.

That is true, both are being replaced by pangolin_data. But it is still the same data being used and `is_designated` is still there in the new pangolin output. 

For reference, the columns currently in the KS report are the following:
`Sample,Selection,Region Code,Ticket,%N_bases,%10X_coverage,QC_pass,Lineage,PangoLEARN_version,VOC,Mutations `
Where PangoLEARN_version should be renamed.

**Comment by sofstam** [comment]
Ok, then it is not a problem then :)

**Comment by talnor** [comment]
For me calling the renamed column `pangolin_version` would be confusing, I would assume we referred to the pangolin software rather than the data used by said software.

I would suggest we either go with `version` as the pangolin team have done in the new format, or we are more explicit and call it `pangolin_data_version`

**Comment by henningonsbring** [comment]
I have just looked at the csv column headers mentioned here, and they mention one header named "pangolin_version": https://cov-lineages.org/resources/pangolin/output.html

Please tell me which index of the column and what the column should be named, or even better, give a suggestion in the PR.

**Comment by talnor** [comment]
Summary:
- pangolin output header to use: `version`
- corresponds to current KS report header: `PangoLEARN_version`
- rename KS report header `PangoLEARN_version` to `pangolin_data_version`
