### ISSUE TITLE
Update variants of concern 

### ISSUE THREAD

**Issue by sofstam** [Clinical-Genomics/MUTANT#146]
BA.4 and BA.5 have been updated as VOCs 
https://www.ecdc.europa.eu/en/covid-19/variants-concern

**What needs to be done:**
The file [classifications.csv](https://github.com/Clinical-Genomics/MUTANT/blob/main/mutant/standalone/classifications.csv) needs to be updated to get the latest changes according to ECDC.

**Suggestions on how to get it done:**
Run the following scripts https://github.com/Clinical-Genomics/MUTANT/tree/main/mutant/standalone/helper_scripts

**Comment by pbiology** [comment]
Will be solved by #118
