### ISSUE TITLE
Integrate code for ECDCs automated variant scanning algorithm

### ISSUE THREAD

**Issue by sylvinite** [Clinical-Genomics/MUTANT#68]
**What needs to be done:**
Put https://github.com/erikalmecdc/ecdc_virology under toolbox

**Suggestions on how to get it done:**
Remote the repo and write a CLI hook.

**What are the arguments for getting it done:**
VoC are currently updated manually. This means it's slow and error prone.
Novel VoC may not be detected before very long time has passed.

**Task is considered finished when:**
A single command in mutant outputs a list of variants of concern / popular variants.

**Comment by talnor** [comment]
New issue [here](https://github.com/Clinical-Genomics/MUTANT/issues/118)
