### ISSUE TITLE
Forward failed samples into KS report

### ISSUE THREAD

**Issue by sylvinite** [Clinical-Genomics/MUTANT#82]
**What needs to be done:**
Samples without fastq files still need to be annotated in KS results report

**Suggestions on how to get it done:**
Read the case config, copypaste into report.py

**What are the arguments for getting it done:**
KS needs to report that all samples have been analyzed downstream

**Task is considered finished when:**
sars-cov results file contain entries for samples that have no fastq data provided into MUTANT

**Comment by sylvinite** [comment]
Tack Henning och Isak

Då kan vi svara ut. Men det vore mycket bra om ni kunde ändra i pipelinen så att alla prov kommer med i results.csv oavsett hur många reads de fått. Vi vill svara ut/avföra alla prov som vi försökt sekvensera från vår aktiva lista. Om de inte finns med i results.csv så är det svårt att säkerställa och automatisera detta. Går det att läsa in i results.csv enligt nedan?

%N_bases: -

%10X_coverage: -

QC_pass: FALSE

Lineage: None

**Comment by talnor** [comment]
Solved as of https://github.com/Clinical-Genomics/MUTANT/pull/91
