### ISSUE TITLE
Add supress to KS report

### ISSUE THREAD

**Issue by sylvinite** [Clinical-Genomics/MUTANT#83]
**What needs to be done:**
Whenever B117 + N501Y + D614G is detected, supress notification of MUTATIONS and suppress notification of VOC.

**Suggestions on how to get it done:**
Add 'Suppressed' to classifications.csv. Implement logic in report python skript

**What are the arguments for getting it done:**
The detection of the above situation makes it really hard for KS personel to see new outbreaks.

**Task is considered finished when:**
When it can be ran on a production ready project (e.g. 864101) and the above mentioned combination is supressed in the result file.

**Comment by talnor** [comment]
Closing. B117 is not relevant anymore and should no longer flood the "voc" results. No current need for this type of function for other types.
