### ISSUE TITLE
Rename fasta headers in consensus files

### ISSUE THREAD

**Issue by talnor** [Clinical-Genomics/MUTANT#86]
**What needs to be done:**
Fasta headers in the consensus sequences currently has the format
`>Consensus_01_SE100_21CS502925.primertrimmed.consensus_threshold_0.75_quality_20`

This should be changed to the following format (regionkod_labkod_customer-sample-name): 
`>01_SE100_SA123456`

**Suggestions on how to get it done:**
Rename output from artic.

**What are the arguments for getting it done:**

**Task is considered finished when:**
Sample consensus files have correct headers.

[20210510.instruktioner_dataoverforing.42ce8feb.txt](https://github.com/Clinical-Genomics/MUTANT/files/6570951/20210510.instruktioner_dataoverforing.42ce8feb.txt)

**Comment by Mropat** [comment]
what do they look like now? we can fix upstream in cg by renaming files correctly

**Comment by talnor** [comment]
They contain all information they need, but the artic analysis adds some extra information to the headers that we need to remove.
