### ISSUE TITLE
Add a downsampling script

### ISSUE THREAD

**Issue by sylvinite** [Clinical-Genomics/MUTANT#88]
**What needs to be done:**
Make a script that takes fastq files and a number, or a percentage. The script randomly subsets the reads in the fastq file(s) to match that number.

**Suggestions on how to get it done:**
Make a little rand loop. Write it in either python or bash. Add to standalone and link to "toolbox subsample"

**What are the arguments for getting it done:**
This sort of script is INCREDIBLY useful, especially for establishing thresholds and debugging weird QC values.

**Task is considered finished when:**
A script under "toolbox subsamle" takes references to fastq files and a number, and produces an output that subsamples the results.

**Comment by pbiology** [comment]
This exists
