### ISSUE TITLE
Automate pangolin updates

### ISSUE THREAD

**Issue by talnor** [Clinical-Genomics/MUTANT#96]
Update docker image with each pangolin update.

Steps:
- [x] Get GMS Dockerhub up and running (ongoing by IS)
- [x] Set up github actions for gms-artic repo
- [x] Set up Mutant to use the image from GMS for Illumina
- [ ] Set up Mutant to use the image from GMS for Nanopore
- [ ] Merge branch to main 

Some inspiration: https://github.com/StaPH-B/docker-builds/blob/2269690e7b80b5b75a5e3e0848ebc0793cb50f34/.github/workflows/pangolin.yml

**Comment by sofstam** [comment]
Maybe we can close this issue at the moment?

**Comment by pbiology** [comment]
A solution is in place
