### ISSUE TITLE
Reads mapped included in multiqc

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/MUTANT#97]
**What needs to be done:**
- Run picard AlignmentSummaryMetrics as part of gms-artic workflow
- Multiqc file to include PCT_PF_READS_ALIGNED metric

**Suggestions on how to get it done:**

**What are the arguments for getting it done:**
Production needs to know the value, otherwise they will have to run microsalt on samples

**Task is considered finished when:**
Multiqc fiile has new metric

**Comment by talnor** [comment]
Done in [gms-artic](https://github.com/genomic-medicine-sweden/gms-artic/pull/20) and [MUTANT](https://github.com/Clinical-Genomics/MUTANT/pull/102)
